
CREATE TABLE [dbo].[LOG](
	[ID] [varchar](40) NOT NULL,
	[OPERATION] [numeric](4, 0) NULL,
	[DATE] [datetime] NOT NULL,
	[MESSAGE] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[TRANSACTIONS](
	[ID] [varchar](40) NOT NULL,
	[DATE] [datetime] NOT NULL,
	[STATUS] [numeric](4, 0) NULL,
	[MESSAGE] [varchar](max) NULL,
 CONSTRAINT [PK_TRANSACTIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
